sudo: false

language: python

python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "pypy"

cache:
  directories:
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
- pip install -r requirements_test.txt
- pip install python-geohash==0.8.5
- pip install -e .
- pip install codecov
- pip install sphinx
- pip install sphinx-rtd-theme

script:
- py.test -v --cov
- cd docs && make doctest

after_success:
- codecov
